title: Satvik Pandey # your name (or website title) here
logo: "/images/satvik-logo.png?raw=true"
description: Aspiring Data Scientist with a Master’s in Computer Science from UIUC, experienced in developing AI solutions during data related internships at Reliance Jio and Auburn Digital Solutions.
theme: jekyll-theme-minimal
email: satvikpandey2022@gmail.com
resume: /assets/resume.pdf
google_analytics: G-FS510NNPX1 # your Google Analytics tracking ID here
