title: Satvik # your name (or website title) here
description: Aspiring Data Scientist with a Master’s in Computer Science from UIUC, experienced in developing AI solutions during data related internships at Reliance Jio and Auburn Digital Solutions.
theme: jekyll-theme-minimal
social:
  - name: LinkedIn
    icon: linkedin
    url: https://www.linkedin.com/in/satvik-pandey-993775167/
google_analytics: G-FS510NNPX1 # your Google Analytics tracking ID here
