title: Satvik Pandey # your name (or website title) here
logo: "/images/satvik-logo.png?raw=true"
description: Engineer at heart and problem-solver by passion, with a Master’s in Computer Science from UIUC. Developed AI-powered solutions during internships at Reliance Jio and research at Forward Data Lab. Excited to explore roles in Data Science, Machine Learning Engineering, and Software Development to craft the future of intelligent systems.
theme: jekyll-theme-minimal
email: satvikpandey2022@gmail.com
resume: /assets/resume.pdf
google_analytics: G-FS510NNPX1 # your Google Analytics tracking ID here
